import pygame
pygame.init()
pygame.font.init()
pygame.mixer.init()
pygame.display.init()
from os.path import join
screen = pygame.display.set_mode((1280, 720))
pygame.display.set_caption("Just Games")
font = pygame.font.Font(None, 120)
screen.fill((0,0,0))
BAR_WIDTH = 400
BAR_HEIGHT = 20
BAR_X = screen.get_width() // 2 - BAR_WIDTH // 2
BAR_Y = screen.get_height() // 2 + 100
BAR_COLOR = (244,71,134)
BAR_BG_COLOR = (50, 50, 50)  # Dark gray background
def show_loading(progress_percent):
    screen.fill((0, 0, 0))
    text = font.render("Loading Assets...", True, (36, 159, 156))
    screen.blit(text, (screen.get_width() // 2 - text.get_width() // 2, screen.get_height() // 2 - text.get_height() // 2))
    pygame.draw.rect(screen, BAR_BG_COLOR, (BAR_X, BAR_Y, BAR_WIDTH, BAR_HEIGHT))
    fill_width = int((progress_percent / 100) * BAR_WIDTH)
    pygame.draw.rect(screen, BAR_COLOR, (BAR_X, BAR_Y, fill_width, BAR_HEIGHT))
    pygame.draw.rect(screen, (100, 100, 100), (BAR_X, BAR_Y, BAR_WIDTH, BAR_HEIGHT), 2)
    pygame.display.flip()
all_player_images = [
        pygame.image.load(join('Images', 'players', f'player{i}.png')).convert_alpha()
        for i in range(1, 24)
    ]
pygame.display.set_icon(all_player_images[0])
show_loading(10)
finalist_suit_image = pygame.image.load(join('Images', 'players', 'finalist_suit.png')).convert_alpha()
background_image = pygame.image.load(join('Images', 'redlight', 'redlight.JPG')).convert()
background_dalgona_image = pygame.image.load(join('Images', 'dalgona', 'playground.jpg')).convert()
background_tugofwar_image = pygame.image.load(join('Images', 'tugofwar', 'tugofwar.jpg')).convert()
background_tugofwar1_image = pygame.image.load(join('Images', 'tugofwar', 'tugofwar1.jpg')).convert()
background_marbles_image = pygame.image.load(join('Images', 'marbles', 'marbles_background.jpg')).convert()
background_marbles1_image = pygame.image.load(join('Images', 'marbles', 'marbles_background1.jpg')).convert()
background_glassbridge_image = pygame.image.load(join('Images', 'glassbridge', 'glassbridge.jpg')).convert()
background_squidgame_image = pygame.image.load(join('Images', 'squidgame', 'squidgame.jpg')).convert()
show_loading(15)
background_squidgame1_image = pygame.image.load(join('Images', 'squidgame', 'squidgame_background1.jpg')).convert()
background_squidgame2_image = pygame.image.load(join('Images', 'squidgame', 'squidgame_background2.jpg')).convert()
background_squidgame3_image = pygame.image.load(join('Images', 'squidgame', 'squidgame_background3.jpg')).convert()
background_squidgame4_image = pygame.image.load(join('Images', 'squidgame', 'squidgame_background4.jpg')).convert()
background_squidgame5_image = pygame.image.load(join('Images', 'squidgame', 'squidgame_background5.jpg')).convert()
background_squidgame6_image = pygame.image.load(join('Images', 'squidgame', 'squidgame_background6.jpg')).convert()
show_loading(20)
background_pentathlon1_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background1.jpg')).convert()
background_pentathlon2_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background2.jpg')).convert()
background_pentathlon3_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background3.jpg')).convert()
background_pentathlon4_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background4.jpg')).convert()
background_pentathlon5_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background5.jpg')).convert()
background_pentathlon6_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background6.jpg')).convert()
background_pentathlon7_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon_background7.jpg')).convert()
show_loading(30)
background_mingle_image = pygame.image.load(join('Images', 'mingle', 'mingle_background.jpg')).convert()
background_mingle1_image = pygame.image.load(join('Images', 'mingle', 'mingle_background1.jpg')).convert()
background_mingle2_image = pygame.image.load(join('Images', 'mingle', 'mingle_background2.jpg')).convert()
start_station_image = pygame.image.load(join('Images', 'pentathlon', 'start-station.jpg')).convert()
walking_image = pygame.image.load(join('Images', 'pentathlon', 'walking.jpg')).convert()
gun_fire_image = pygame.image.load(join('Images', 'pentathlon', 'fire.jpg')).convert()
pass_image = pygame.image.load(join('Images', 'pentathlon', 'pass.jpg')).convert()
fail_image = pygame.image.load(join('Images', 'pentathlon', 'fail.jpg')).convert()
show_loading(35)
ddakji_station_image = pygame.image.load(join('Images', 'pentathlon', 'ddakji-station.jpg')).convert()
flying_stone_station_image = pygame.image.load(join('Images', 'pentathlon', 'flying-stone-station.jpg')).convert()
gonggi_station_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi-station.jpg')).convert()
spinning_top_station_image = pygame.image.load(join('Images', 'pentathlon', 'spinningtop-station.jpg')).convert()
jegi_station_image = pygame.image.load(join('Images', 'pentathlon', 'jegi-station.jpg')).convert()
ddakji_pass_image = pygame.image.load(join('Images', 'pentathlon', 'ddakji-flipped.jpg')).convert()
stone_pass_image = pygame.image.load(join('Images', 'pentathlon', 'stone-pass.jpg')).convert()
stone_fail_image = pygame.image.load(join('Images', 'pentathlon', 'stone-fail.jpg')).convert()
gonggi_pass_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi-pass.jpg')).convert()
spinningtop_pass_image = pygame.image.load(join('Images', 'pentathlon', 'spinningtop-pass.jpg')).convert()
spinningtop_fail_image = pygame.image.load(join('Images', 'pentathlon', 'spinningtop-fail.jpg')).convert()
jegi_fail_image = pygame.image.load(join('Images', 'pentathlon', 'jegi-fail.jpg')).convert()
pentathlon_win_image = pygame.image.load(join('Images', 'pentathlon', 'pentathlon-win.jpg')).convert()
show_loading(40)
doll_image = pygame.image.load(join('Images', 'redlight', 'doll.png')).convert_alpha()
doll_forward_image = pygame.image.load(join('Images', 'redlight', 'dollforward.png')).convert_alpha()
dalgona_image = pygame.image.load(join('Images', 'dalgona', 'dalgona.png')).convert_alpha()
dormitory_image = pygame.image.load(join('Images', 'dormitory.jpg')).convert()
stone_image = pygame.image.load(join('Images', 'pentathlon', 'stone.png')).convert_alpha()
show_loading(50)
stone_throw_image = pygame.image.load(join('Images', 'pentathlon', 'stone-throw.png')).convert_alpha()
blue_circle_gonggi_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi', 'blue-circle-gonggi.png')).convert_alpha()
green_triangle_gonggi_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi', 'green-triangle-gonggi.png')).convert_alpha()
purple_square_gonggi_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi', 'purple-square-gonggi.png')).convert_alpha()
red_circle_gonggi_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi', 'red-circle-gonggi.png')).convert_alpha()
yellow_triangle_gonggi_image = pygame.image.load(join('Images', 'pentathlon', 'gonggi', 'yellow-triangle-gonggi.png')).convert_alpha()
spinning_top_image = pygame.image.load(join('Images', 'pentathlon', 'spinningtop.png')).convert_alpha()
jegi_image = pygame.image.load(join('Images', 'pentathlon', 'jegi.png')).convert_alpha()
show_loading(55)
shape_images = {
    "triangle": pygame.image.load(join('Images', 'dalgona', 'triangledalgona.png')).convert_alpha(),
    "star": pygame.image.load(join('Images', 'dalgona', 'stardalgona.png')).convert_alpha(),
    "circle": pygame.image.load(join('Images', 'dalgona', 'circledalgona.png')).convert_alpha(),
    "umbrella": pygame.image.load(join('Images', 'dalgona', 'umbrelladalgona.png')).convert_alpha(),
}
needle_img = pygame.image.load(join('Images', 'dalgona', 'needle.png')).convert_alpha()
glass_image = pygame.image.load(join('Images', 'glassbridge', 'glass.jpg')).convert()
knife_image = pygame.image.load(join('Images', 'squidgame', 'knife.png')).convert_alpha()
blue_ddakji_image = pygame.image.load(join('Images', 'ddakji', 'blue-ddakji.png')).convert_alpha()
red_ddakji_image = pygame.image.load(join('Images', 'ddakji', 'red-ddakji.png')).convert_alpha()
show_loading(60)
crack_images = [
    pygame.image.load(join('Images', 'dalgona', 'cracks0.png')).convert_alpha(),  # no cracks
    pygame.image.load(join('Images', 'dalgona', 'cracks1.png')).convert_alpha(),  # light cracks
    pygame.image.load(join('Images', 'dalgona', 'cracks2.png')).convert_alpha(),  # more cracks
    pygame.image.load(join('Images', 'dalgona', 'cracks3.png')).convert_alpha(),  # heavy cracks
    pygame.image.load(join('Images', 'dalgona', 'cracks4.png')).convert_alpha(),  # almost broken
]
hide_knife_image = pygame.image.load(join('Images', 'hide', 'knife.png')).convert_alpha()
door_image = pygame.image.load(join('Images', 'hide', 'door.jpg')).convert()
hide_background_image = pygame.image.load(join('Images', 'hide', 'hide_background.jpg')).convert()
stairs_image = pygame.image.load(join('Images', 'hide', 'stairs.jpg')).convert()
key_image = pygame.image.load(join('Images', 'hide', 'key.png')).convert_alpha()
key_image = pygame.transform.scale(key_image, (20, 24))
red_image = pygame.image.load(join('Images', 'hide', 'red.png')).convert_alpha()
blue_image = pygame.image.load(join('Images', 'hide', 'blue.png')).convert_alpha()
show_loading(70)
ddakji_background1_image = pygame.image.load(join('Images', 'ddakji_background1.jpg')).convert()
ddakji_background2_image = pygame.image.load(join('Images', 'ddakji_background2.jpg')).convert()
ddakji_background3_image = pygame.image.load(join('Images', 'ddakji_background3.jpg')).convert()
ddakji_background4_image = pygame.image.load(join('Images', 'ddakji_background4.jpg')).convert()
ddakji_background5_image = pygame.image.load(join('Images', 'ddakji_background5.jpg')).convert()
ddakji_background6_image = pygame.image.load(join('Images', 'ddakji_background6.jpg')).convert()
ddakji_background7_image = pygame.image.load(join('Images', 'ddakji_background7.jpg')).convert()
ddakji_background8_image = pygame.image.load(join('Images', 'ddakji_background8.jpg')).convert()
ddakji_background9_image = pygame.image.load(join('Images', 'ddakji_background9.jpg')).convert()
ddakji_background10_image = pygame.image.load(join('Images', 'ddakji_background10.jpg')).convert()
ddakji_background11_image = pygame.image.load(join('Images', 'ddakji_background11.jpg')).convert()
ddakji_background12_image = pygame.image.load(join('Images', 'ddakji_background12.jpg')).convert()
ddakji_background13_image = pygame.image.load(join('Images', 'ddakji_background13.jpg')).convert()
show_loading(75)
justgame_image = pygame.image.load(join('Images', 'ui', 'justgame.png')).convert_alpha()
freeplay_image = pygame.image.load(join('Images', 'ui', 'freeplay.jpg')).convert()
storymode_image = pygame.image.load(join('Images', 'ui', 'storymode.jpg')).convert()
playerselect_image = pygame.image.load(join('Images', 'ui', 'playerselect.jpg')).convert()
back_image = pygame.image.load(join('Images', 'ui', 'back.jpg')).convert()
equip_image = pygame.image.load(join('Images', 'ui', 'equip.jpg')).convert()
unequip_image = pygame.image.load(join('Images', 'ui', 'unequip.jpg')).convert()
redlight_button_image = pygame.image.load(join('Images', 'ui', 'redlightgreenlight_button.jpg')).convert()
dalgona_button_image = pygame.image.load(join('Images', 'ui', 'dalgona_button.jpg')).convert()
tugofwar_button_image = pygame.image.load(join('Images', 'ui', 'tugofwar_button.jpg')).convert()
marbles_button_image = pygame.image.load(join('Images', 'ui', 'marbles_button.jpg')).convert()
glass_bridge_button_image = pygame.image.load(join('Images', 'ui', 'glassbridge_button.jpg')).convert()
squidgame_button_image = pygame.image.load(join('Images', 'ui', 'squidgame_button.jpg')).convert()
season1_button_image = pygame.image.load(join('Images', 'ui', 'season1_button.jpg')).convert()
season2_button_image = pygame.image.load(join('Images', 'ui', 'season2_button.jpg')).convert()
season3_button_image = pygame.image.load(join('Images', 'ui', 'season3_button.jpg')).convert()
pentathlon_button_image = pygame.image.load(join('Images', 'ui', 'pentathlon_button.jpg')).convert()
show_loading(80)
mingle_button_image = pygame.image.load(join('Images', 'ui', 'mingle_button.jpg')).convert()
hide_button_image = pygame.image.load(join('Images', 'ui', 'hide_button.jpg')).convert()
jumprope_button_image = pygame.image.load(join('Images', 'ui', 'jumprope_button.jpg')).convert()
hide_background1_image = pygame.image.load(join('Images', 'hide', 'hide_background1.jpg')).convert()
hide_background2_image = pygame.image.load(join('Images', 'hide', 'hide_background2.jpg')).convert()
jump_background_image = pygame.image.load(join('Images', 'jumprope', 'jumprope_background.jpg')).convert()
jump_background2_image = pygame.image.load(join('Images', 'jumprope', 'jumprope_background2.jpg')).convert()
doll1_image = pygame.image.load(join('Images', 'jumprope', 'doll1.png')).convert_alpha()
doll2_image = pygame.image.load(join('Images', 'jumprope', 'doll2.png')).convert_alpha()
doll1house_image = pygame.image.load(join('Images', 'jumprope', 'doll1house.png')).convert_alpha()
doll2house_image = pygame.image.load(join('Images', 'jumprope', 'doll2house.png')).convert_alpha()
maintheme = pygame.mixer.Sound(join('Music', 'maintheme.mp3'))
dorm = pygame.mixer.Sound(join('Music', 'dorm.mp3'))
money = pygame.mixer.Sound(join('Music', 'money.mp3'))
intro_voice = pygame.mixer.Sound(join("Music", "redlight_intro.mp3"))
dalgona_intro_voice = pygame.mixer.Sound(join("Music", "dalgona_intro.mp3"))
tugofwar_intro_voice = pygame.mixer.Sound(join("Music", "tugofwar_intro.mp3"))
marbles_intro_voice = pygame.mixer.Sound(join("Music", "marbles_intro.mp3"))
glassbridge_intro_voice = pygame.mixer.Sound(join("Music", "glassbridge_intro.mp3"))
squidgame_intro_voice = pygame.mixer.Sound(join("Music", "squidgame_intro.mp3"))
squidgame_voiceline1 = pygame.mixer.Sound(join("Music", "squidgame_voiceline1.mp3"))
show_loading(85)
squidgame_voiceline2 = pygame.mixer.Sound(join("Music", "squidgame_voiceline2.mp3"))
squidgame_voiceline3 = pygame.mixer.Sound(join("Music", "squidgame_voiceline3.mp3"))
squidgame_end = pygame.mixer.Sound(join("Music", "squidgame_end.mp3"))
gunshot_sound = pygame.mixer.Sound(join("Music", "gunshot.mp3"))
doll5_sound = pygame.mixer.Sound(join("Music", "doll5.mp3"))
doll4_sound = pygame.mixer.Sound(join("Music", "doll4.mp3"))
doll3_sound = pygame.mixer.Sound(join("Music", "doll3.mp3"))
doll2_sound = pygame.mixer.Sound(join("Music", "doll2.mp3"))
flymetothemoon_sound = pygame.mixer.Sound(join("Music", "flymetothemoon.mp3"))
flymetothemoon_remix_sound = pygame.mixer.Sound(join("Music", "flymetothemoon_remix.mp3"))
dalgona_theme = pygame.mixer.Sound(join('Music', 'dalgona.mp3'))
dalgona_scratch = pygame.mixer.Sound(join('Music', 'dalgona-scratch.mp3'))
dalgona_crack = pygame.mixer.Sound(join('Music', 'dalgona-crack.mp3'))
tugofwar_theme = pygame.mixer.Sound(join('Music', 'tugofwar.mp3'))
show_loading(90)
marbles_theme = pygame.mixer.Sound(join('Music', 'marbles.mp3'))
glassbridge_theme = pygame.mixer.Sound(join("Music", "glassbridge.mp3"))
glassbridge_collapse = pygame.mixer.Sound(join("Music", "glassbridge_collapse.mp3"))
glass_shatter = pygame.mixer.Sound(join("Music", "glass_shatter.mp3"))
rain_theme = pygame.mixer.Sound(join("Music", "rain.mp3"))
pentathlon_intro_voice = pygame.mixer.Sound(join("Music", "pentathlon_intro.mp3"))
pentathlon_theme = pygame.mixer.Sound(join("Music", "pentathlon.mp3"))
pentathlon_champion_theme = pygame.mixer.Sound(join("Music", "pentathlon_champion.mp3"))
pentathlon_victory = pygame.mixer.Sound(join("Music", "pentathlon_victory.mp3"))
fail_sound = pygame.mixer.Sound(join("Music", "fail.mp3"))
pass_sound = pygame.mixer.Sound(join("Music", "pass.mp3"))
one_two_sound = pygame.mixer.Sound(join("Music", "one_two.mp3"))
gun_shot_sound = pygame.mixer.Sound(join("Music", "gun_shot.mp3"))
show_loading(95)
story_ddakji_intro_voice = pygame.mixer.Sound(join("Music", "story_ddakji_intro.mp3"))
story_ddakji_firstfail = pygame.mixer.Sound(join("Music", "story_ddakji_firstfail.mp3"))
story_ddakji_secondfail = pygame.mixer.Sound(join("Music", "story_ddakji_secondfail.mp3"))
story_ddakji_win = pygame.mixer.Sound(join("Music", "story_ddakji_win.mp3"))
mingle_intro_voice = pygame.mixer.Sound(join("Music", "mingle_intro.mp3"))
mingle_theme = pygame.mixer.Sound(join("Music", "mingle.mp3"))
mingle_chaos = pygame.mixer.Sound(join("Music", "mingle_chaos.mp3"))
mingle_welcomeback = pygame.mixer.Sound(join("Music", "mingle_welcomeback.mp3"))
hide_intro_voice = pygame.mixer.Sound(join("Music", "hide_intro.mp3"))
hide_theme = pygame.mixer.Sound(join("Music", "hide.mp3"))
unlock = pygame.mixer.Sound(join("Music", "unlock.mp3"))
jump_theme = pygame.mixer.Sound(join("Music", "jumprope.mp3"))
jump_intro_voice = pygame.mixer.Sound(join("Music", "jump_intro.mp3"))
show_loading(100)