import pygame
from sys import exit
from assets import background_image, background_dalgona_image, background_tugofwar1_image, background_marbles_image, background_marbles1_image, background_glassbridge_image
from assets import background_squidgame_image, background_squidgame1_image, background_squidgame2_image, background_squidgame3_image, background_squidgame4_image, background_squidgame5_image
from assets import background_squidgame6_image, background_pentathlon1_image, background_pentathlon2_image, background_pentathlon3_image, background_pentathlon4_image
from assets import background_pentathlon5_image, background_pentathlon6_image, background_pentathlon7_image, background_mingle_image, background_mingle2_image
from assets import ddakji_background1_image, ddakji_background2_image, ddakji_background3_image, ddakji_background4_image, ddakji_background5_image, ddakji_background6_image
from assets import ddakji_background7_image, ddakji_background8_image, ddakji_background9_image, ddakji_background10_image, ddakji_background11_image, ddakji_background12_image, ddakji_background13_image
from assets import doll_image, doll_forward_image, intro_voice, dalgona_intro_voice, tugofwar_intro_voice, marbles_intro_voice, glassbridge_intro_voice, squidgame_intro_voice, squidgame_end
from assets import pentathlon_intro_voice, story_ddakji_intro_voice, story_ddakji_firstfail, story_ddakji_secondfail, story_ddakji_win, mingle_intro_voice, hide_intro_voice, hide_background1_image
from assets import hide_background2_image, jump_intro_voice, jump_background2_image, sky_intro_voice, sky_background_image
from resize import game_surface, is_fullscreen, handle_resize, toggle_fullscreen, render_to_screen
def play_intro_and_show_subtitles(sub_num=1):
    match sub_num: 
        case 1: #redlight
            subtitles = [
                ("첫 번째 게임은 '레드 라이트, 그린 라이트'입니다", 
                "The first game is Red Light, Green Light.", 
                8000, background_image),
                ("태그하는 사람이 '녹색불, 빨간불'이라고 소리치는 동안 앞으로 나아갈 수 있습니다.", 
                "You can move forward while the tagger shouts, 'Green Light, red light.'", 
                6000, background_image),
                ("만약 당신의 움직임이 나중에 감지된다면, 당신은 탈락하게 될 것입니다.", 
                "If your movement is detected afterward, you will be eliminated.", 
                4000, background_image),
                ("5분 안에 잡히지 않고 결승선을 통과하는 사람들", 
                "Those who cross the finish line without getting caught in five minutes", 
                5000, background_image),
                ("이번 라운드를 통과하세요.", 
                "pass this round.", 
                2000, background_image),
                ("그럼 게임을 시작해 볼까요.", 
                "Then let the game begin.", 
                2000, background_image),
            ]
        case 2: #dalgona
            subtitles = [
                ("두 번째 게임은 달고나입니다.", 
                "The second game is Dalgona.", 
                3000, background_dalgona_image),
                ("당신이 선택한 모양은 당신이 추출해야 할 모양입니다.", 
                "The shape you have chosen is the shape you must extract.", 
                4000, background_dalgona_image),
                ("제한시간은 10분입니다.", 
                "The time limit is ten minutes.", 
                3000, background_dalgona_image),
                ("10분 안에 모양을 깨끗하게 추출하면 합격입니다.", 
                "Cleanly extract the shape in ten minutes, and you pass.", 
                5000, background_dalgona_image),
                ("게임을 시작해 봅시다.", 
                "Let the game begin.", 
                3000, background_dalgona_image),
            ]
        case 3: #tugofwar
            subtitles = [
                ("세 번째 게임에 오신 것을 환영합니다.", 
                "Welcome to the third game.", 
                4000, background_tugofwar1_image),
                ("이 게임은 줄다리기입니다.", 
                "This game is Tug-of-War.", 
                3000, background_tugofwar1_image),
                ("당신은 그 탑에 밧줄을 당겨야 합니다.", 
                "You will pull on a rope on that tower.", 
                4000, background_tugofwar1_image),
                ("상대를 쓰러뜨리면 승리합니다.", 
                "Make your opponents fall and you win.", 
                4000, background_tugofwar1_image),
            ]
        case 4: #marbles
            subtitles = [
                ("각자 한 봉지씩 가져가세요.", 
                "Please take one pouch each.", 
                8000, background_marbles_image),
                ("각 주머니에는 구슬이 10개 들어 있습니다.", 
                "There are ten marbles in each pouch.", 
                4000, background_marbles_image),
                ("몇 개 있는지 확인해 보세요.", 
                "Please check how many there are.", 
                5000, background_marbles1_image),
                ("이 게임에서는 10개의 구슬을 사용해 옆에 있는 파트너와 경쟁합니다. ", 
                "In this game, use your ten marbles to compete with the partner next to you.", 
                7000, background_marbles1_image),
                ("파트너에게서 구슬 10개를 모두 가져가는 사람이 승리합니다.", 
                "The player who takes all ten marbles from their partner wins.", 
                5000, background_marbles1_image),
                ("시간은 30분입니다.", 
                "You have 30 minutes.", 
                4000, background_marbles1_image),
                ("게임을 시작하자.", 
                "Let the games begin.", 
                2000, background_marbles1_image),
            ]
        case 5: #glassbridge
            subtitles = [
                ("플레이어 여러분, 다섯 번째 게임에 오신 것을 환영합니다.", 
                "Players, welcome to the fifth game.", 
                4000, background_glassbridge_image),
                ("다섯 번째 게임은 유리 발판돌입니다.", 
                "The fifth game is Glass Stepping Stones.", 
                5000, background_glassbridge_image),
                ("각 발판은 1종 또는 2종의 유리로 구성되어 있으며,", 
                "Each stepping stone is made of one or two types of glass,", 
                3000, background_glassbridge_image),
                ("강화유리와 일반유리.", 
                "tempered glass and normal glass.", 
                4000, background_glassbridge_image),
                ("강화 유리는 두 명의 플레이어의 무게도 견딜 수 있습니다.", 
                "Tempered glass can even withstand the weight of two players.", 
                5000, background_glassbridge_image),
                ("하지만 일반 유리는 한 사람만으로도 깨질 수 있습니다.", 
                "But normal glass will shatter just with one person.", 
                4000, background_glassbridge_image),
                ("플레이어는 두 개의 타일 중 어느 것을 선택할지 결정해야 합니다.", 
                "Players, you will decide which one of the two tiles", 
                4000, background_glassbridge_image),
                ("강화 유리로 만들어졌습니다.", 
                "is made of tempered glass,", 
                3000, background_glassbridge_image),
                ("그리고 18쌍의 타일을 통과하면서 그 위를 밟으세요.", 
                "and step on those as you pass through 18 pairs of tiles.", 
                4000, background_glassbridge_image),
                ("만약 당신이 안전하게 반대편으로 건너간다면, 당신은 통과한 것입니다.", 
                "If you safely cross to the other side, you pass.", 
                5000, background_glassbridge_image),
                ("시간은 16분입니다.", 
                "You have 16 minutes.", 
                3000, background_glassbridge_image),
                ("다리를 건너려면 16분이 걸립니다.", 
                "You have 16 minutes to cross the bridge.", 
                3000, background_glassbridge_image),
                ("그럼 게임을 시작해 볼까요.", 
                "Then let the game begin.", 
                4000, background_glassbridge_image),
            ]
        case 6: #squidgame intro
            subtitles = [
                ("마지막 게임에 오신 것을 환영합니다.", 
                "Welcome to the final game.", 
                3000, background_squidgame1_image),
                ("여섯 번째이자 마지막 게임은 '오징어 게임'입니다.", 
                "The sixth and final game is Squid Game.", 
                4000, background_squidgame1_image),
                ("오징어 게임의 규칙을 설명해 드리겠습니다.", 
                "Let me explain the rules of Squid Game.", 
                4000, background_squidgame_image),
                ("한 플레이어가 게임을 진행할 수 없는 경우,", 
                "If one player is unable to proceed with the game,", 
                4000, background_squidgame_image),
                ("마지막까지 살아남는 사람이 승리합니다.", 
                "the last one standing wins.", 
                2000, background_squidgame_image),
                ("이제 게임을 시작해 보겠습니다.", 
                "Now, let the game begin.", 
                3000, background_squidgame_image),
            ]
        case 7: #squidgame end
            subtitles = [
                ("승리를 축하합니다.", 
                "Congratulations on your victory.", 
                1000, background_squidgame2_image),
                ("정말 재밌는 경기였습니다.", 
                "It was quite the game.", 
                5000, background_squidgame2_image),
                ("당신들은 말입니다.", 
                "You people are horses.", 
                2000, background_squidgame2_image),
                ("경마장의 말들.", 
                "Horses at a racetrack.", 
                4000, background_squidgame2_image),
                ("예상치 못한 일이었습니다.", 
                "It was unexpected.", 
                3000, background_squidgame2_image),
                ("이렇게 멀리까지 올 줄은 생각지 못했어요.", 
                "I didn't think you'd run this far.", 
                5000, background_squidgame2_image),
                ("그냥 꿈이라고 생각해 보세요.", 
                "Just think of it as a dream.", 
                5000, background_squidgame2_image),
                ("어차피 당신에게는 나쁜 꿈이 아니었잖아요.", 
                "It wasn't a bad dream for you anyway.", 
                2000, background_squidgame2_image),
                ("", 
                "", 
                2000, background_squidgame3_image),
                ("당신은...", 
                "Do you...", 
                2000, background_squidgame4_image),
                ("아직", 
                "still", 
                3000, background_squidgame4_image),
                ("사람을 믿는가?", 
                "have faith in people?", 
                1000, background_squidgame4_image),
                ("당신이 겪어온 모든 일 이후에요?", 
                "After all you've been through?", 
                4000, background_squidgame4_image),
                ("왜 나를 만나고 싶어했니?", 
                "Why did you want to see me?", 
                3000, background_squidgame4_image),
                ("나는 들었다", 
                "I heard", 
                2000, background_squidgame4_image),
                ("너는 상금을 아직 건드리지 않았구나", 
                "you haven't touched your prize money", 
                4000, background_squidgame4_image),
                ("그리고 다시 옛날의 생활로 돌아갔습니다.", 
                "and have gone back to living your old life.", 
                3000, background_squidgame4_image),
                ("그 돈", 
                "That money", 
                2000, background_squidgame4_image),
                ("네가 받은 보상은 무엇이었나", 
                "was the reward you got", 
                3000, background_squidgame4_image),
                ("당신의 행운과 노고에 감사드립니다.", 
                "for your luck and hard work.", 
                2000, background_squidgame4_image),
                ("당신은 그것을 사용할 권리가 있습니다.", 
                "You have the right to use it.", 
                5000, background_squidgame4_image),
                ("인생이란...", 
                "Life is...", 
                4000, background_squidgame4_image),
                ("짧은.", 
                "short.", 
                1000, background_squidgame4_image),
                ("왜 그런 짓을 했나요?", 
                "Why did you do such a thing?", 
                5000, background_squidgame4_image),
                ("당신은 알고 있나요", 
                "Do you know", 
                2000, background_squidgame4_image),
                ("돈이 없는 사람이", 
                "what someone with no money", 
                5000, background_squidgame4_image),
                ("돈이 너무 많은 사람과 공통점이 있나요?", 
                "has in common with someone with too much money?", 
                10000, background_squidgame4_image),
                ("생활", 
                "Living", 
                3000, background_squidgame4_image),
                ("그들에게는 재미없는 일이다.", 
                "is no fun for them.", 
                5000, background_squidgame4_image),
                ("돈이 너무 많으면,", 
                "If you have too much money,", 
                3000, background_squidgame4_image),
                ("무엇을 사든, 무엇을 먹든, 무엇을 마시든", 
                "no matter what you buy, eat, or drink,", 
                7000, background_squidgame4_image),
                ("결국에는 모든 것이 지루해진다.", 
                "everything gets boring in the end.", 
                7000, background_squidgame4_image),
                ("어느 시점에서,", 
                "At some point,", 
                2000, background_squidgame4_image),
                ("제 고객들은 모두 똑같은 말을 하기 시작했습니다.", 
                "all my clients began to tell me the same thing.", 
                6000, background_squidgame4_image),
                ("그들은 더 이상 삶의 기쁨을 느끼지 못했습니다.", 
                "That they had no joy in life anymore.", 
                9000, background_squidgame4_image),
                ("그래서 우리는 모두 모였습니다", 
                "So, we all got together", 
                5000, background_squidgame4_image),
                ("그리고 곰곰히 생각해 보았습니다.", 
                "and did some pondering.", 
                4000, background_squidgame4_image),
                ("우리는 무엇을 할 수 있나요", 
                "What can we do", 
                3000, background_squidgame4_image),
                ("재미있게 놀고 싶어?", 
                "to have some fun?", 
                3000, background_squidgame4_image),
                ("재미있는?", 
                "Fun?", 
                6000, background_squidgame4_image),
                ("당신은 우리에게 그 모든 일을 겪게 하셨습니다...", 
                "You put us through all that...", 
                4000, background_squidgame4_image),
                ("재미로?", 
                "for fun?", 
                1000, background_squidgame4_image),
                ("잘 들어보세요.", 
                "Listen carefully.", 
                3000, background_squidgame5_image),
                ("나는 말이 아니다.", 
                "I'm not a horse.", 
                3000, background_squidgame5_image),
                ("나는 사람이에요.", 
                "I'm a person.", 
                4000, background_squidgame5_image),
                ("그래서 알고 싶어요", 
                "That's why I want to know", 
                3000, background_squidgame5_image),
                ("당신들은 누구인가...", 
                "who you people are...", 
                5000, background_squidgame5_image),
                ("그리고 어떻게 사람들에게 그런 잔혹한 짓을 저지를 수 있는지.", 
                "and how you can commit such atrocities against people.", 
                4000, background_squidgame5_image),
                ("터무니없는 생각은 하지 마세요.", 
                "Don't get any absurd ideas.", 
                2000, background_squidgame5_image),
                ("그래서...", 
                "That's why...", 
                3000, background_squidgame5_image),
                ("나는 당신을 용서할 수 없습니다", 
                "I can't forgive you", 
                3000, background_squidgame5_image),
                ("당신이 하는 모든 일에 대해서요.", 
                "for everything you're doing.", 
                2000, background_squidgame5_image),
                ("그냥 비행기에 타세요.", 
                "Just get on that plane.", 
                2000, background_squidgame5_image),
                ("그건 당신에게 좋은 일이에요.", 
                "It's for your own good.", 
                12000, background_squidgame5_image),
                ("", 
                "", 
                31000, background_squidgame6_image),
            ]
        case 8: #pentathlon
            subtitles = [
                ("두 번째 게임에 오신 것을 환영합니다.", 
                "Welcome to your second game.", 
                6000, background_pentathlon1_image),
                ("이 게임은 팀 단위로 진행됩니다.", 
                "This game will be played in teams.", 
                3000, background_pentathlon1_image),
                ("당신이 플레이할 게임은 6각5종 경기입니다.", 
                "The game you will be playing is Six-Legged Pentathlon.", 
                5000, background_pentathlon2_image),
                ("다리를 묶은 상태에서 시작합니다.", 
                "You will start with your legs tied together.", 
                4000, background_pentathlon2_image),
                ("각 멤버는 10미터 지점마다 미니 게임을 번갈아가며 플레이합니다,", 
                "Each member will take turns playing a mini-game at every ten-meter mark,", 
                5000, background_pentathlon2_image),
                ("그리고 만약 당신이 승리한다면, 그 팀은 다음 팀으로 진출할 수 있습니다.", 
                "and if you win, the team can move on to the next one.", 
                3000, background_pentathlon2_image),
                ("미니 게임은 다음과 같습니다.", 
                "Here are the mini-games.", 
                2000, background_pentathlon2_image),
                ("첫 번째는 딱지입니다.", 
                "Number one, the Ddakji.", 
                2000, background_pentathlon3_image),
                ("두 번째, 플라잉 스톤.", 
                "Number two, Flying Stone.", 
                2000, background_pentathlon4_image),
                ("세 번째, 공기.", 
                "Number three, Gong-gi.", 
                3000, background_pentathlon5_image),
                ("네 번째, 팽이.", 
                "Number four, Spinning Top.", 
                2000, background_pentathlon6_image),
                ("다섯 번째, 제기.", 
                "Number five, Jegi.", 
                3000, background_pentathlon7_image),
                ("당신의 목표는 모든 미니 게임에서 승리하는 것입니다", 
                "Your goal is to win all the mini-games", 
                3000, background_pentathlon2_image),
                ("그리고 5분 안에 결승선을 통과합니다.", 
                "and cross the finish line in five minutes.", 
                4000, background_pentathlon2_image),
                ("게임을 시작해 볼까요.", 
                "Let the game begin.", 
                3000, background_pentathlon2_image),
            ]
        case 9: #storyddakji intro
            subtitles = [
                ("선생님.", 
                "Sir.", 
                4000, ddakji_background1_image),
                ("나랑 게임할래?", 
                "Would you like to play a game with me?", 
                2000, ddakji_background1_image),
                ("선생님, 전에 딱지치기를 해보셨나요?", 
                "Sir, you've played ddakji before, haven't you?", 
                5000, ddakji_background1_image),
                ("나랑 딱지치기 하자.", 
                "Play ddakji with me.", 
                3000, ddakji_background1_image),
                ("당신이 이길 때마다 10만원을 드리겠습니다.", 
                "Each time you win, I will give you 100,000 won.", 
                3000, ddakji_background1_image),
                ("잠깐만요, 그럼 내가 당신의 딱지를 뒤집으면,", 
                "Wait, so if I flip your ddakji over,", 
                3000, ddakji_background1_image),
                ("10만원 주실래요?", 
                "you'll give me 100,000 won?", 
                2000, ddakji_background1_image),
                ("하지만 제가 이길 때마다 10만원씩 주셔야 합니다.", 
                "However, each time I win, you must give me 100,000 won.", 
                9000, ddakji_background1_image),
                ("나는 당신을 먼저 보내줄게요.", 
                "I'll let you go first.", 
                3000, ddakji_background1_image),
            ]
        case 10: #storyddakji first fail
            subtitles = [
                ("", 
                "", 
                300, ddakji_background2_image),
                ("돈이 없나요?", 
                "Do you not have any money?", 
                1000, ddakji_background3_image),
                ("돈...", 
                "Money...", 
                4000, ddakji_background3_image),
                ("그러면 몸으로 돈을 지불하면 됩니다.", 
                "Then you can pay with your body.", 
                2000, ddakji_background3_image),
                ("내 몸?", 
                "My body?", 
                1000, ddakji_background3_image),
                ("이게 뭐야?", 
                "What the hell?", 
                4000, ddakji_background4_image),
                ("한 번 때리면 10만원씩 깎아주겠습니다.", 
                "I'll shave off 100,000 won per slap.", 
                4000, ddakji_background4_image),
                ("한 라운드 더.", 
                "One more round.", 
                1000, ddakji_background5_image),
            ]
        case 11: #storyddakji second etc. fail
            subtitles = [
                ("", 
                "", 
                250, ddakji_background2_image),
                ("", 
                "", 
                250, ddakji_background4_image),
                ("또 한 라운드!", 
                "Another round!", 
                1000, ddakji_background5_image),
            ]
        case 12: #storyddakji win
            subtitles = [
                ("", 
                "", 
                1000, ddakji_background6_image),
                ("내가 이겼어! 봤지?", 
                "I won! See that?", 
                2000, ddakji_background6_image),
                ("봤어? 내가 이겼어!", 
                "Did you see that? I won!", 
                3000, ddakji_background6_image),
                ("이리 와. 얼굴을 이리 와.", 
                "Come here. Get your face over here.", 
                4000, ddakji_background7_image),
                ("그만둬, 멍청아.", 
                "Let go of this, you jerk.", 
                3000, ddakji_background7_image),
                ("여기 10만원이 있습니다.", 
                "Here's your 100,000 won.", 
                5000, ddakji_background8_image),
                ("축하해요.", 
                "Congratulations.", 
                7000, ddakji_background8_image),
                ("오른쪽.", 
                "Right.", 
                2000, ddakji_background8_image),
                ("나는 10만원을 받는다.", 
                "I get 100,000 won.", 
                3000, ddakji_background8_image),
                ("선생님.", 
                "Sir.", 
                2000, ddakji_background9_image),
                ("이런 게임을 며칠만 플레이해도 큰 돈을 벌 수 있습니다.", 
                "You can make big money playing games like this for a few days.", 
                4000, ddakji_background9_image),
                ("시도해 보시겠습니까?", 
                "Would you like to give it a try?", 
                5000, ddakji_background9_image),
                ("남은 자리가 많지 않아요.", 
                "We don't have many spots left.", 
                6000, ddakji_background10_image),
                ("전화 주세요.", 
                "Give me a call.", 
                2000, ddakji_background10_image),
                ("안녕하세요.", 
                "Hello.", 
                5000, ddakji_background11_image),
                ("나는...", 
                "I'm...", 
                2000, ddakji_background11_image),
                ("오늘 오후에 당신 명함을 받은 사람이에요.", 
                "the guy who got your business card this afternoon.", 
                3000, ddakji_background11_image),
                ("게임에 참여하고 싶으신가요?", 
                "Do you wish to participate in the game?", 
                2000, ddakji_background11_image),
                ("참여를 원하시면 이름과 생년월일을 알려주세요.", 
                "If you wish to participate, please state your name and birthdate.", 
                4000, ddakji_background11_image),
                ("비밀번호?", 
                "The password?", 
                5000, ddakji_background12_image),
                ("빨간불, 초록불.", 
                "Red light, green light.", 
                5000, ddakji_background12_image),
                ("", 
                "", 
                11000, ddakji_background13_image),
            ]
        case 13: #mingle
            subtitles = [
                ("세 번째 게임에 오신 것을 환영합니다.", 
                "Welcome to your third game.", 
                3000, background_mingle2_image),
                ("당신이 플레이할 게임은 밍글입니다.", 
                "The game you will be playing is Mingle.", 
                4000, background_mingle2_image),
                ("모든 플레이어는 중앙 플랫폼으로 나오세요.", 
                "All players, please step onto the center platform.", 
                5000, background_mingle_image),
                ("게임이 시작되면 플랫폼이 회전하기 시작합니다.", 
                "When the game starts, the platform will begin to rotate,", 
                3000, background_mingle_image),
                ("그러면 숫자가 들릴 거예요.", 
                "and you will hear a number.", 
                2000, background_mingle_image),
                ("그 크기의 그룹을 형성해야 합니다.", 
                "You must form groups of that size,", 
                4000, background_mingle_image),
                ("방으로 들어가서 30초 이내에 문을 닫으세요.", 
                "go into the rooms, and close the door within 30 seconds.", 
                3000, background_mingle_image),
                ("게임을 시작해 봅시다.", 
                "Let the game begin.", 
                3000, background_mingle_image),
            ]
        case 14: #hide n seek intro
            subtitles = [
                ("네 번째 게임에 오신 것을 환영합니다.", 
                "Welcome to your fourth game.", 
                3000, hide_background1_image),
                ("이 경기는 두 팀으로 진행됩니다.", 
                "This game will be played in two teams.", 
                4000, hide_background1_image),
                ("당신이 플레이할 게임은 숨바꼭질입니다.", 
                "The game you will be playing is Hide-and-seek.", 
                5000, hide_background1_image),
                ("블루팀은 30분 이내에 출구를 찾아 탈출해야 합니다.", 
                "The Blue Team must either find the exit and escape within 30 minutes", 
                5000, hide_background2_image),
                ("아니면 시간이 끝날 때까지 레드팀에게서 숨어있으세요.", 
                "or stay hidden from the Red Team until the time is up.", 
                4000, hide_background2_image),
                ("태그하는 레드팀은 블루팀 멤버를 찾아야 합니다.", 
                "The Red Team, the taggers, must find members of the Blue Team", 
                4000, hide_background2_image),
                ("30분 안에 그들을 죽여라.", 
                "and kill them within 30 minutes.", 
                3000, hide_background2_image),
                ("상대 플레이어를 죽이지 못하면 탈락하게 됩니다.", 
                "If you fail to kill any opposing players, you will be eliminated.", 
                3000, hide_background2_image),
                ("당신은 경기장 문의 열쇠를 받았습니다.", 
                "You have been given keys to doors in the arena.", 
                6000, hide_background2_image),
                ("그 열쇠를 사용하면 문을 통과할 수 있습니다.", 
                "You can use that key to go through the doors,", 
                4000, hide_background2_image),
                ("하지만 문이 한 번 열리면 다시 잠글 수 없습니다.", 
                "but once a door is unlocked, it cannot be relocked.", 
                4000, hide_background2_image),
                ("레드팀은 칼을 사용해 블루팀을 공격할 수 있습니다.", 
                "The Red Team can use knives to attack the Blue Team.", 
                5000, hide_background2_image),
                ("하지만 레드팀 구성원끼리는 서로를 공격할 수 없습니다.", 
                "However, members of the Red Team are not allowed to attack each other.", 
                4000, hide_background2_image),
                ("게임이 잠시 후에 시작됩니다.", 
                "The game will begin momentarily.", 
                4000, hide_background2_image),
            ]
        case 15: #jump rope intro
            subtitles = [
                ("다섯 번째 게임에 오신 것을 환영합니다.", 
                "Welcome to the fifth game.", 
                5000, jump_background2_image),
                ("당신이 플레이할 게임은 점프 로프입니다.", 
                "The game you will be playing is Jump Rope.", 
                5000, jump_background2_image),
                ("회전하는 로프를 뛰어넘어 다리를 건너야 합니다.", 
                "You must cross the bridge as you jump over the rotating rope", 
                5000, jump_background2_image),
                ("20분 안에 반대편에 도착할 수 있어요.", 
                "and get to the other side within 20 minutes.", 
                5000, jump_background2_image),
                ("이제 게임을 시작해 보겠습니다.", 
                "Now, let the game begin.", 
                4000, jump_background2_image),
            ]
        case 16: #sky squid game intro
            subtitles = [
                ("결승전에 참여해주신 모든 분들을 진심으로 환영합니다.", 
                "A warm welcome to all of you for joining the final game.", 
                6000, sky_background_image),
                ("마지막 게임은 스카이 스퀴드 게임입니다.", 
                "The final game is Sky Squid Game.", 
                5000, sky_background_image),
                ("게임 규칙은 다음과 같습니다.", 
                "Here are the rules of the game.", 
                5000, sky_background_image),
                ("플레이어들은 사각형, 삼각형, 원형 ​​탑에서 게임을 진행합니다.", 
                "Players will play on the square, triangle, and circle towers.", 
                6000, sky_background_image),
                ("여러분은 이 세 기둥을 중심으로 밀고 당기는 게임을 하게 될 것입니다.", 
                "You will play a pushing game on these three pillars.", 
                6000, sky_background_image),
                ("첫 번째 라운드는 현재 여러분이 있는 사각형 탑에서 진행됩니다.", 
                "The first round will be played on the square tower you are currently on.", 
                4000, sky_background_image),
                ("한 명 이상의 플레이어를 탑에서 밀어 떨어뜨리면", 
                "If you push one or more players off the tower", 
                3000, sky_background_image),
                ("그들이 아직 살아 있는 동안,", 
                "while they are still alive,", 
                2000, sky_background_image),
                ("남은 모든 플레이어는 다음 라운드를 위해 삼각형 탑으로 이동합니다.", 
                "all remaining players will move on to the triangle tower for the next round.", 
                5000, sky_background_image),
                ("마찬가지로, 한 명 이상의 플레이어를 탈락시키는 경우에도 마찬가지입니다.", 
                "Likewise, if you eliminate one or more players", 
                3000, sky_background_image),
                ("두 번째 라운드의 삼각형 탑에서,", 
                "on the triangle tower in the second round,", 
                4000, sky_background_image),
                ("이제 원형 탑으로 이동하시게 됩니다.", 
                "you will move on to the circle tower.", 
                3000, sky_background_image),
                ("원형 탑에서의 마지막 라운드에도 동일하게 적용됩니다.", 
                "The same applies to the final round on the circle tower.", 
                3000, sky_background_image),
                ("한 명 이상의 선수를 밀어내면,", 
                "If you push one or more players off,", 
                2000, sky_background_image),
                ("탑에 남아 있는 모든 사람이 최종 승자가 될 것입니다.", 
                "everyone remaining on the tower will be the final winners.", 
                5000, sky_background_image),
                ("꼭 기억해 주세요", 
                "Please keep in mind", 
                2000, sky_background_image),
                ("제한 시간 내에 아무도 탈락시키지 못하면,", 
                "that if you do not eliminate anyone within the time limit,", 
                5000, sky_background_image),
                ("탑 위에 있는 모든 사람이 제거될 것이다.", 
                "everyone on the tower will be eliminated.", 
                3000, sky_background_image),
                ("첫 번째 라운드를 시작하려면 바닥에 있는 버튼을 눌러주세요.", 
                "Please press the button on the ground to start the first round.", 
                7000, sky_background_image),
            ]
    intro_voice_channel = pygame.mixer.Channel(7)
    match sub_num:
        case 1:
            intro_voice_channel.play(intro_voice)
        case 2:
            intro_voice_channel.play(dalgona_intro_voice)
        case 3:
            intro_voice_channel.play(tugofwar_intro_voice)
        case 4:
            intro_voice_channel.play(marbles_intro_voice)
        case 5:
            intro_voice_channel.play(glassbridge_intro_voice)
        case 6:
            intro_voice_channel.play(squidgame_intro_voice)
        case 7:
            intro_voice_channel.play(squidgame_end)
        case 8:
            intro_voice_channel.play(pentathlon_intro_voice)
        case 9:
            intro_voice_channel.play(story_ddakji_intro_voice)
        case 10:
            intro_voice_channel.play(story_ddakji_firstfail)
        case 11:
            intro_voice_channel.play(story_ddakji_secondfail)
        case 12:
            intro_voice_channel.play(story_ddakji_win)
        case 13:
            intro_voice_channel.play(mingle_intro_voice)
        case 14:
            intro_voice_channel.play(hide_intro_voice)
        case 15:
            intro_voice_channel.play(jump_intro_voice)
        case 16:
            intro_voice_channel.play(sky_intro_voice)
    font_korean = pygame.font.SysFont("malgungothic", 34)
    font_english = pygame.font.SysFont("Arial", 30)
    clock = pygame.time.Clock()
    doll_intro_image = doll_forward_image
    for kr, en, duration, intro_background_image in subtitles:
        start_time = pygame.time.get_ticks()
        running = True
        while running:
            clock.tick(5)
            now = pygame.time.get_ticks()
            for event in pygame.event.get():
                match event.type: 
                    case pygame.QUIT:
                        exit()
                    case pygame.VIDEORESIZE:
                        handle_resize(event.w, event.h)
                    case pygame.KEYDOWN:
                        if event.key == pygame.K_F11:
                            toggle_fullscreen()
                        elif event.key == pygame.K_ESCAPE and is_fullscreen:
                            toggle_fullscreen()
            # Draw background and other
            game_surface.blit(intro_background_image, (0, 0))
            if sub_num == 1:
                game_surface.blit(doll_intro_image, (1080, 315))
            # Draw subtitles
            kr_text = font_korean.render(kr, True, (255, 255, 255))
            en_text = font_english.render(en, True, (255, 0, 0))
            game_surface.blit(kr_text, (game_surface.get_width()//2 - kr_text.get_width()//2, 560))
            game_surface.blit(en_text, (game_surface.get_width()//2 - en_text.get_width()//2, 600))
            render_to_screen()
            # Wait for the specific duration
            if now - start_time >= duration:
                doll_intro_image = doll_image
                running = False