from random import randint
from assets import all_player_images
class Player:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.eliminated = False
        self.ddakji_flipped = False
        self.next_game = False
        self.team = None
        self.clicks = 0
        self.tug_won = False
        self.marbles = 10
        self.marbles_bet = None
        self.marbles_guess = None
        self.marbles_turn = False
        self.marbles_won = False
        self.glass_ready = False       
        self.glass_choice = None       
        self.glass_step = 0            
        self.glass_side = 0            
        self.glass_win = False 
        self.health = 100
        self.knife_active = False
        self.knife_direction = "left"
        self.hit_player_id = None
        self.pentathlon_ddakji_flipped = False
        self.stone_hit = False
        self.gonggi_caught = False
        self.spinning = False
        self.jegi_pass = False
        self.pentathlon_win = False
        self.in_door = False
        self.mingle_win = False
        self.in_door_id = None
        self.voted = False
        self.baby_picked = False
sprite_id = randint(0, 22)
player_image = all_player_images[sprite_id]
player1 = Player(0, 620)
def reset_player():
    player1.x = 0
    player1.y = 620
    player1.eliminated = False
    player1.ddakji_flipped = False
    player1.next_game = False
    player1.team = None
    player1.clicks = 0
    player1.tug_won = False
    player1.marbles = 10
    player1.marbles_bet = None
    player1.marbles_guess = None
    player1.marbles_turn = False
    player1.marbles_won = False
    player1.glass_ready = False       
    player1.glass_choice = None    
    player1.glass_step = 0            
    player1.glass_side = 0            
    player1.glass_win = False 
    player1.health = 100
    player1.knife_active = False
    player1.knife_direction = "left"
    player1.hit_player_id = None
    player1.pentathlon_ddakji_flipped = False
    player1.stone_hit = False
    player1.gonggi_caught = False
    player1.spinning = False
    player1.jegi_pass = False
    player1.pentathlon_win = False
    player1.in_door = False
    player1.mingle_win = False
    player1.in_door_id = None